---
name: Docker Registry Scanner Syntax Checks

on:
  workflow_call:

permissions: read-all

jobs:
  syntax:
    name: Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true

      - name: Install YAMLlint, PyLint, Flake8 and Black
        run: python -m pip install --user pylint flake8 black yamllint

      - name: Run YAMLlint
        run: yamllint --strict .

      - name: Run PyLint
        run: python -m pylint --recursive yes .

      - name: Run Flake8
        run: python -m flake8 .

      - name: Run Black
        run: python -m black --diff --check --color .
